/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscacep;

import classes.PesqCep;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Luiz Henrique
 */
public class TelaCep extends javax.swing.JFrame {

    /**
     * Creates new form TelaCep
     */
    public TelaCep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRua = new javax.swing.JTextField();
        lblBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblUF = new javax.swing.JTextField();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(438, 322));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CEP :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 62, 34, 25));

        TxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCepActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 64, 83, -1));

        jLabel2.setText("Rua :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 132, 35, 23));

        jLabel3.setText("Bairro :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 168, 50, 23));

        jLabel4.setText("Cidade :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 202, 55, 20));
        getContentPane().add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 133, 296, -1));
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 171, 296, -1));
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 202, 204, -1));

        jLabel5.setText("UF :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 202, -1, 20));
        getContentPane().add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 202, 58, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cep.jpg"))); // NOI18N
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 11, 239, 103));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCepActionPerformed
       
        PesqCep pega = new PesqCep();
        try 
        {
            lblRua.setText(pega.getEndereco(TxtCep.getText()));
            lblBairro.setText(pega.getBairro(TxtCep.getText()));
            lblCidade.setText(pega.getCidade(TxtCep.getText()));
            lblUF.setText(pega.getUF(TxtCep.getText()));
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(TelaCep.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_TxtCepActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon imagem = new  ImageIcon(TelaCep.class.getResource("/Imagens/cep.jpg"));
        
            Image imag = imagem.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_DEFAULT);
        
            lblImagem.setIcon(new ImageIcon(imag));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lblBairro;
    private javax.swing.JTextField lblCidade;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField lblRua;
    private javax.swing.JTextField lblUF;
    // End of variables declaration//GEN-END:variables
}
